### ISSUE TITLE
When nesting complex-ui, you can't use define definitionsCallback as a string

### ISSUE THREAD

**Issue by slyadams** [OptimalBPM/angular-schema-form-complex-ui#2]
You can define nested "definitionCallbacks" to be strings like:

`"definitionsCallback": $scope.getDefinitions2`

But you cannot do:

`"definitionsCallback": "getDefinitions2"`

Plunker: https://plnkr.co/edit/3C4kspCj5yjtnTe0Ows1?p=preview

**Comment by nicklasb** [comment]
Ok, good call. 
I see no way of fixing that as the add-on has no way of finding the right scope to look in.
Because it looks in its parent scope for the function.
I will add a mention in the documentation.

**Comment by nicklasb** [comment]
Added description in docs, closing.
If you have problems setting the function, because you store the form server side in text format, you can try to search and replace the string with the function when the schema is loaded.
